services:
  telegram-bot-base:
    build: .
    image: telegram-bot-base
    container_name: telegram-bot-base
    restart: unless-stopped
    mem_limit: 512m
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
